In [1]:
import pandas as pd

# Entrepôts de données 2025-2026 TP

## Partie A : étude des données sources

### 1. Pour chaque fichier, indiquer, selon vous, quel est le type/la nature des données qu'il contient ?

In [2]:
tb_customer_data_df = pd.read_csv("polytech2025edd_tp_source/tb_customer_data.csv")
tb_customer_data_df.head(3)

,customer_id,account_num,lname,fname,mi,address1,address2,address3,address4,city,...,gender,total_children,num_children_at_home,education,date_accnt_opened,member_card,occupation,houseowner,num_cars_owned,fullname
0,1,87462024688,Nowmer,Sheri,A.,2433 Bailey Road,NaN,NaN,NaN,Tlaxiaco,...,F,4,2,Partial High School,1991-09-10,Bronze,Skilled Manual,Y,4,Sheri Nowmer
1,2,87470586299,Whelply,Derrick,I.,2219 Dewing Avenue,NaN,NaN,NaN,Sooke,...,M,1,0,Partial High School,1993-03-11,Bronze,Professional,N,3,Derrick Whelply
2,3,87475757600,Derry,Jeanne,NaN,7640 First Ave.,NaN,NaN,NaN,Issaquah,...,F,1,1,Bachelors Degree,1991-06-11,Bronze,Professional,Y,2,Jeanne Derry

In [3]:
tb_customer_data_df.dtypes

customer_id               int64
account_num               int64
lname                    object
fname                    object
mi                       object
address1                 object
address2                 object
address3                float64
address4                float64
city                     object
state_province           object
postal_code               int64
country                  object
customer_region_id        int64
phone1                   object
phone2                   object
birthdate                object
marital_status           object
yearly_income            object
gender                   object
total_children            int64
num_children_at_home      int64
education                object
date_accnt_opened        object
member_card              object
occupation               object
houseowner               object
num_cars_owned            int64
fullname                 object
dtype: object

Cette 1ère table contient les informations personnelles des clients.  
Il y a tout type de données : String, Int, Date, etc.

In [4]:
tb_personne_data_df = pd.read_csv("polytech2025edd_tp_source/tb_personne_data.csv")
tb_personne_data_df.head(3)

   pid    pnom  pprenom pgenre  page  ptaille     pville
0    1  Dupond     Jean      H  30.0      1.7      Paris
1    2  Durand  Jacques      H  20.0      NaN  Marseille
2    3  Dupuis   Pierre      H   NaN      NaN      Lille

In [5]:
tb_personne_data_df.dtypes

pid          int64
pnom        object
pprenom     object
pgenre      object
page       float64
ptaille    float64
pville      object
dtype: object

Cette table contient les informations personnelles des clients.  
Il y a tout type de données : String, Int, etc.

In [6]:
tb_product_class_data_df = pd.read_csv("polytech2025edd_tp_source/tb_product_class_data.csv")
tb_product_class_data_df.head(3)

,product_class_id,product_subcategory,product_category,product_department,product_family
0,1,Nuts,Specialty,Produce,Food
1,2,Shellfish,Seafood,Seafood,Food
2,3,Canned Fruit,Fruit,Canned Products,Food

In [7]:
tb_product_class_data_df.dtypes

product_class_id        int64
product_subcategory    object
product_category       object
product_department     object
product_family         object
dtype: object

Cette table contient les informations sur les différentes classes de produit : catégorie, sous-catégorie, etc.  
Il y a tout type de données : String, Int, etc.

In [8]:
tb_product_data_df = pd.read_csv("polytech2025edd_tp_source/tb_product_data.csv")
tb_product_data_df.head(3)

,product_class_id,product_id,brand_name,product_name,SKU,SRP,gross_weight,net_weight,recyclable_package,low_fat,units_per_case,cases_per_pallet,shelf_width,shelf_height,shelf_depth
0,30,1,Washington,Washington Berry Juice,90748583674,2.85,8.39,6.39,f,f,30,14,16.9,12.60,7.40
1,52,2,Washington,Washington Mango Drink,96516502499,0.74,7.42,4.42,f,t,18,8,13.4,3.71,22.60
2,52,3,Washington,Washington Strawberry Drink,58427771925,0.83,13.10,11.10,t,t,17,13,14.4,11.00,7.77

In [9]:
tb_product_data_df.dtypes

product_class_id        int64
product_id              int64
brand_name             object
product_name           object
SKU                     int64
SRP                   float64
gross_weight          float64
net_weight            float64
recyclable_package     object
low_fat                object
units_per_case          int64
cases_per_pallet        int64
shelf_width           float64
shelf_height          float64
shelf_depth           float64
dtype: object

Cette table contient les informations personnelles des produits, en particulier leur classe, marque, nom, etc.  
Il y a tout type de données : String, Int, etc.

In [10]:
tb_promotion_data_df = pd.read_csv("polytech2025edd_tp_source/tb_promotion_data.csv")
tb_promotion_data_df.head(3)

,promotion_id,promotion_district_id,promotion_name,media_type,cost,start_date,end_date
0,0,0,No Promotion,No Media,0.0,NaN,NaN
1,1,110,High Roller Savings,Product Attachment,14435.0,1996-01-03 00:00:00,1996-01-06 00:00:00
2,2,110,Green Light Special,Product Attachment,8907.0,1996-01-18 00:00:00,1996-01-20 00:00:00

In [11]:
tb_promotion_data_df.dtypes

promotion_id               int64
promotion_district_id      int64
promotion_name            object
media_type                object
cost                     float64
start_date                object
end_date                  object
dtype: object

Cette table contient les informations sur les promotions liées aux produits : prix, date, nom, etc.  
Il y a tout type de données : String, Int, Date, etc.

In [12]:
tb_region_data_df = pd.read_csv("polytech2025edd_tp_source/tb_region_data.csv")
tb_region_data_df.head(3)

,region_id,sales_city,sales_state_province,sales_district,sales_region,sales_country,sales_district_id
0,0,NaN,NaN,No District,No Region,No Country,0
1,1,San Francisco,CA,San Francisco,Central West,USA,123
2,2,Mexico City,DF,Mexico City,Mexico Central,Mexico,118

In [13]:
tb_region_data_df.dtypes

region_id                int64
sales_city              object
sales_state_province    object
sales_district          object
sales_region            object
sales_country           object
sales_district_id        int64
dtype: object

Cette table contient les informations sur les différentes régions de ventes de produit.  
Il y a tout type de données : String, Int, etc.

In [14]:
tb_sales_fact_1997_data_df = pd.read_csv("polytech2025edd_tp_source/tb_sales_fact_1997_data.csv")
tb_sales_fact_1997_data_df.head(3)

,product_id,time_id,customer_id,promotion_id,store_id,store_sales,store_cost,unit_sales
0,337,371,6280,0,2,1.50,0.5100,2.0
1,1512,371,6280,0,2,1.62,0.6318,3.0
2,963,371,4018,0,2,2.40,0.7200,1.0

In [15]:
tb_sales_fact_1997_data_df.dtypes

product_id        int64
time_id           int64
customer_id       int64
promotion_id      int64
store_id          int64
store_sales     float64
store_cost      float64
unit_sales      float64
dtype: object

Cette table de faits contient les informations sur les ventes de produits.  
Il y a tout type de données : String, Int, etc.

In [16]:
tb_store_data_df = pd.read_csv("polytech2025edd_tp_source/tb_store_data.csv")
tb_store_data_df.head(3)

,store_id,store_type,region_id,store_name,store_number,store_street_address,store_city,store_state,store_postal_code,store_country,...,last_remodel_date,store_sqft,grocery_sqft,frozen_sqft,meat_sqft,coffee_bar,video_store,salad_bar,prepared_food,florist
0,0,HeadQuarters,0,HQ,0,1 Alameda Way,Alameda,CA,55555,USA,...,NaN,NaN,NaN,NaN,NaN,f,f,f,f,f
1,1,Supermarket,28,Store 1,1,2853 Bailey Rd,Acapulco,Guerrero,55555,Mexico,...,1990-12-05 00:00:00,23593.0,17475.0,3671.0,2447.0,f,f,f,f,f
2,2,Small Grocery,78,Store 2,2,5203 Catanzaro Way,Bellingham,WA,55555,USA,...,1973-06-04 00:00:00,28206.0,22271.0,3561.0,2374.0,t,f,f,f,f

In [17]:
tb_store_data_df.dtypes

store_id                  int64
store_type               object
region_id                 int64
store_name               object
store_number              int64
store_street_address     object
store_city               object
store_state              object
store_postal_code         int64
store_country            object
store_manager            object
store_phone              object
store_fax                object
first_opened_date        object
last_remodel_date        object
store_sqft              float64
grocery_sqft            float64
frozen_sqft             float64
meat_sqft               float64
coffee_bar               object
video_store              object
salad_bar                object
prepared_food            object
florist                  object
dtype: object

Cette contient les informations personnelles des différents magasins : nom, localisation, manager, etc.  
Il y a tout type de données : String, Int, etc.

In [18]:
tb_time_by_day_data_df = pd.read_csv("polytech2025edd_tp_source/tb_time_by_day_data.csv")
tb_time_by_day_data_df.head(3)

,time_id,the_date,the_day,the_month,the_year,day_of_month,week_of_year,month_of_year,quarter,fiscal_period
0,738,1998-01-07 00:00:00,Wednesday,January,1998,7,4,1,Q1,NaN
1,739,1998-01-08 00:00:00,Thursday,January,1998,8,4,1,Q1,NaN
2,740,1998-01-09 00:00:00,Friday,January,1998,9,4,1,Q1,NaN

In [19]:
tb_time_by_day_data_df.dtypes

time_id            int64
the_date          object
the_day           object
the_month         object
the_year           int64
day_of_month       int64
week_of_year       int64
month_of_year      int64
quarter           object
fiscal_period    float64
dtype: object

C'est une table des dates comme on peut en trouver dans les rapports Power BI pour pouvoir filtrer les dates par mois, années, etc.

### 2. Pour mieux comprendre encore le contenu de ces fichiers, quel est, selon vous, le sens des attributs suivants :  
### - Attribut mi du fichier tb_customer_data.csv
### - Attributs SKU et SRP du fichier tb_product_data.csv

In [20]:
tb_customer_data_df.head(3)

,customer_id,account_num,lname,fname,mi,address1,address2,address3,address4,city,...,gender,total_children,num_children_at_home,education,date_accnt_opened,member_card,occupation,houseowner,num_cars_owned,fullname
0,1,87462024688,Nowmer,Sheri,A.,2433 Bailey Road,NaN,NaN,NaN,Tlaxiaco,...,F,4,2,Partial High School,1991-09-10,Bronze,Skilled Manual,Y,4,Sheri Nowmer
1,2,87470586299,Whelply,Derrick,I.,2219 Dewing Avenue,NaN,NaN,NaN,Sooke,...,M,1,0,Partial High School,1993-03-11,Bronze,Professional,N,3,Derrick Whelply
2,3,87475757600,Derry,Jeanne,NaN,7640 First Ave.,NaN,NaN,NaN,Issaquah,...,F,1,1,Bachelors Degree,1991-06-11,Bronze,Professional,Y,2,Jeanne Derry

In [21]:
tb_customer_data_df["mi"].unique()

array(['A.', 'I.', nan, 'J.', 'F.', 'H.', 'C.', 'M.', 'V.', 'K.', 'G.',
       'S.', 'P.', 'N.', 'B.', 'D.', 'E.', 'R.', 'L.', 'W.', 'A. C.',
       'T.', 'Z', 'O.', 'Y.', 'S', 'L', 'J', ' ', 'Z.', 'Dog', 'M', 'P',
       'A', 'G', 'H', 'W', 'U.', 'E', 'Alvarez', 'K', 'l.', 'D', 'B',
       'Q.', 'R', 'T', 'P. L.', 'M. K.', 'K..', 'N', 'A..', 'J. R.',
       'L. F.', 'C', 'X.', 'A. J.', 'V. M.', 'Wl', 'M. N. M.', 'L..',
       'D. R.', 'E. T.', 'J. O.', 'F'], dtype=object)

In [22]:
tb_product_data_df.head(3)

,product_class_id,product_id,brand_name,product_name,SKU,SRP,gross_weight,net_weight,recyclable_package,low_fat,units_per_case,cases_per_pallet,shelf_width,shelf_height,shelf_depth
0,30,1,Washington,Washington Berry Juice,90748583674,2.85,8.39,6.39,f,f,30,14,16.9,12.60,7.40
1,52,2,Washington,Washington Mango Drink,96516502499,0.74,7.42,4.42,f,t,18,8,13.4,3.71,22.60
2,52,3,Washington,Washington Strawberry Drink,58427771925,0.83,13.10,11.10,t,t,17,13,14.4,11.00,7.77

In [23]:
tb_product_data_df[["SKU", "SRP"]]

              SKU   SRP
0     90748583674  2.85
1     96516502499  0.74
2     58427771925  0.83
3     64412155747  3.64
4     85561191439  2.19
...           ...   ...
1555  29538288712  2.65
1556  50687324404  1.20
1557  84930775761  2.16
1558  75317577719  1.62
1559  54896665215  1.60

[1560 rows x 2 columns]

Le SKU semble faire référence au Stock Keeping Unit permettant de identifié les produits dans l'inventaire.  
D'un autre coté, le SRP semble faire référence au Suggested Retail Price qui correspond au prix de vente conseillé du produit.

### 3. En utilisant la correspondance entre les noms des attributs, proposer un schéma dans le format souhaité (schéma relationnel, entité/association, diagramme UML) permettant de modéliser les liens entre les différentes données.  
### Les noms des entités sont issus des noms de fichiers (tb_"entité"_data.csv).

---

## Partie B : analyse des données

### 1. Quel est le classement des produits suivant leur nombre de ventes (Unit Sales) ?  
### Donner un résultat partiel.

In [24]:
nb_ventes_produits_df = (
    tb_sales_fact_1997_data_df
    .groupby("product_id")
    .apply(lambda x: pd.Series({"nb_ventes": x["unit_sales"].sum()}))
    .sort_values(by="nb_ventes", ascending=False)
)

nb_ventes_produits_df

C:\Users\natha\AppData\Local\Temp\ipykernel_23988\3820128152.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({"nb_ventes": x["unit_sales"].sum()}))

            nb_ventes
product_id
952             267.0
549             258.0
1452            257.0
948             252.0
404             246.0
...               ...
257             104.0
1551             97.0
209              94.0
1                83.0
1559             79.0

[1559 rows x 1 columns]

### 2. Quels sont les 10 produits les plus vendus (Unit Sales) ?

In [25]:
nb_ventes_produits_df.head(10)

            nb_ventes
product_id
952             267.0
549             258.0
1452            257.0
948             252.0
404             246.0
609             245.0
455             243.0
414             242.0
928             240.0
1428            239.0

### 3. Quel est l'identifiant, la marque et le nom du produit le plus vendu (Unit Sales) ?

In [26]:
product_id_plus_vendu = nb_ventes_produits_df.index[0]
product_plus_vendu_df = tb_product_data_df[tb_product_data_df["product_id"] == product_id_plus_vendu]
product_plus_vendu_df[["product_id", "brand_name", "product_name"]]

     product_id brand_name         product_name
951         952    Special  Special Wheat Puffs

### 4. Proposer un programme permettant de retrouver le résultat de la requête MDX 2 (transparent 35 du cours), sans que l'affichage soit forcément identique.

In [27]:
sales_by_months_df = (
    tb_sales_fact_1997_data_df
    .merge(tb_time_by_day_data_df[tb_time_by_day_data_df.the_year == 1997], on="time_id", how="inner")
    .groupby("month_of_year", as_index=False)
    .apply(lambda x: pd.Series({"Unit Sales": x["unit_sales"].sum()}))
    .sort_values("month_of_year")
    .rename({"month_of_year": "Time"}, axis=1)
    .set_index("Time")
)

sales_by_months_df

C:\Users\natha\AppData\Local\Temp\ipykernel_23988\1585014762.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({"Unit Sales": x["unit_sales"].sum()}))

      Unit Sales
Time
1        21628.0
2        20957.0
3        23706.0
4        20179.0
5        21081.0
6        21350.0
7        23763.0
8        21697.0
9        20388.0
10       19958.0
11       25270.0
12       26796.0

### 5. Proposer un programme permettant de retrouver le résultat de la requête MDX 4 (transparent 39 du cours), sans que l'affichage soit forcément identique

In [28]:
sales_by_months_quarter_df = (
    tb_sales_fact_1997_data_df
    .merge(tb_time_by_day_data_df[tb_time_by_day_data_df.the_year == 1997], on="time_id", how="inner")
    .groupby(["month_of_year", "quarter"], as_index=False)
    .apply(lambda x: pd.Series({"Unit Sales": x["unit_sales"].sum()}))
)

sales_by_quarters_df = (
    sales_by_months_quarter_df
    .groupby("quarter")
    .apply(lambda x: pd.Series({"Unit Sales Quarter": x["Unit Sales"].sum()}))
)

sales_by_months2_df = (
    sales_by_months_quarter_df
    .merge(sales_by_quarters_df, on="quarter")
    .sort_values(["Unit Sales Quarter", "Unit Sales"], ascending=False)
    .set_index("month_of_year")
)

sales_by_months2_df[["Unit Sales"]]

C:\Users\natha\AppData\Local\Temp\ipykernel_23988\2547778483.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({"Unit Sales": x["unit_sales"].sum()}))
C:\Users\natha\AppData\Local\Temp\ipykernel_23988\2547778483.py:11: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({"Unit Sales Quarter": x["Unit Sales"].sum()}))

               Unit Sales
month_of_year
12                26796.0
11                25270.0
10                19958.0
3                 23706.0
1                 21628.0
2                 20957.0
7                 23763.0
8                 21697.0
9                 20388.0
6                 21350.0
5                 21081.0
4                 20179.0

### 6. Proposer un programme permettant de retrouver le résultat de la requête MDX 7 (transparent 45 du cours), sans que l'affichage soit forcément identique.

In [29]:
sales_by_months_df

      Unit Sales
Time
1        21628.0
2        20957.0
3        23706.0
4        20179.0
5        21081.0
6        21350.0
7        23763.0
8        21697.0
9        20388.0
10       19958.0
11       25270.0
12       26796.0

In [34]:
evo_sales_by_months_df = sales_by_months_df.copy()
evo_sales_by_months_df["Unit SalesM-1"] = evo_sales_by_months_df["Unit Sales"].shift(1)
evo_sales_by_months_df["Evolution"] = evo_sales_by_months_df["Unit Sales"] > evo_sales_by_months_df["Unit SalesM-1"]
evo_sales_by_months_df["Evolution"].replace({False: "-", True: "+"}, inplace=True)
evo_sales_by_months_df["Evolution"].iloc[0] = None
evo_sales_by_months_df

C:\Users\natha\AppData\Local\Temp\ipykernel_23988\2470551689.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  evo_sales_by_months_df["Evolution"].replace({False: "-", True: "+"}, inplace=True)
C:\Users\natha\AppData\Local\Temp\ipykernel_23988\2470551689.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  evo_sales_by_months_df["Evolution"].iloc[0] = None

      Unit Sales  Unit SalesM-1 Evolution
Time
1        21628.0            NaN      None
2        20957.0        21628.0         -
3        23706.0        20957.0         +
4        20179.0        23706.0         -
5        21081.0        20179.0         +
6        21350.0        21081.0         +
7        23763.0        21350.0         +
8        21697.0        23763.0         -
9        20388.0        21697.0         -
10       19958.0        20388.0         -
11       25270.0        19958.0         +
12       26796.0        25270.0         +